server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/reading_story_web_db}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: ${DBMS_PASSWORD:root}
    username: ${DBMS_USERNAME:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  redis:
    host: localhost
    port: 6379
    timeout: 10000

app:
  brevo:
    apikey: ${BREVO_API_KEY}
    url: https://api.brevo.com
  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUDNAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}
  jwt:
    secretKey: ${JWT_SECRETKEY:iamvietanh<3}
    access-duration: 3600 # in second
    refreshable-duration: 36000 # in seconds
  folder:
    avatar: "avatar_folder"
    chapter: "chapter_folder"
    story: "story_folder"
    avatar-frame: "avatar_frame_folder"
  admin-email: ${ADMIN_EMAIL:numberzero0909@gmail.com}
  frontend:
    url: ${FRONTEND_URL:http://localhost:5173}