server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

spring:
  datasource
    url: jdbc:mysql://root:trmAKIhIVbVtfRdiMGkTaKYOsriztgui@yamanote.proxy.rlwy.net:35566/railway
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQLUSER:root}
    password: ${MYSQLPASSWORD:trmAKIhIVbVtfRdiMGkTaKYOsriztgui}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    
  redis:
    host: ${REDISHOST:shuttle.proxy.rlwy.net}
    port: ${REDISPORT:43580}
    password: ${REDISPASSWORD:xGJQrIuPdTLqbyBQengrSyTUmuKgbTKM}
    username: ${REDISUSER:default}
    timeout: 10000

app:
  brevo:
    apikey: ${BREVO_API_KEY:<your-api-key>}
    url: https://api.brevo.com
  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUDNAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}
  jwt:
    secretKey: ${JWT_SECRETKEY:iamvietanh<3}
    access-duration: 3600 # in seconds
    refreshable-duration: 36000 # in seconds
  folder:
    avatar: "avatar_folder"
    chapter: "chapter_folder"
    story: "story_folder"
    avatar-frame: "avatar_frame_folder"
  admin-email: ${ADMIN_EMAIL:numberzero0909@gmail.com}
  frontend:
    url: ${FRONTEND_URL:https://v-story.vercel.app}
