server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reading_story_web_db
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  redis:
    host: localhost
    port: 6379
    #password: your_redis_password
    timeout: 10000

app:
  brevo:
    apikey: <your-api-key>
    url: https://api.brevo.com
  cloudinary:
    cloud-name: <cloud-name>
    api-key: <api-key>
    api-secret: <api-sercet>
  jwt:
    secretKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
    access-duration: 3600 # in second
    refreshable-duration: 36000 # in seconds
  folder:
    avatar: "avatar_folder"
    chapter: "chapter_folder"
    story: "story_folder"
    avatar-frame: "avatar_frame_folder"
  frontend:
    url: "http://localhost:3000"